data:
  system_type: saddle_system
  test_size: 1000
  val_size: 1000
loss:
  entropy_decay_proportion: 0.5
  entropy_weight: 0.19228049282664503
  state_loss_type: mse
  state_loss_weight: 1.0
  use_entropy_decay: true
  use_entropy_reg: true
  value_loss_type: null
  value_loss_weight: 0.3
meta:
  db_path: datasets/results/multi_saddle_8.db
  output_dir: neural_networks/output/test_subprocess
  run_id: test_batch
  seed: 42
model:
  ema_decay: 0.8473013014327047
  encoder_init_method: he
  hidden_dim: 32
  initial_temp: 3.7169034184910754
  min_temp: 0.3424253466291911
  num_states: 4
  predictor_type: standard
  use_gumbel: true
  use_target_encoder: true
  value_method: angle
training:
  batch_size: 128
  checkpoint_every: 25
  epochs: 75
  lr: 0.0006017038731893062
  min_lr: 6.017038731893062e-05
  optimizer_type: adamw
  restart_mult: 1
  restart_period: 20
  scheduler_type: cosine
  use_warmup: true
  warmup_epochs: 10
  weight_decay: 0.010164460859566581
